base/urls.py
from django.urls import path, include
from . import views
from django.conf import settings
from django.conf.urls.static import static

app_name = 'base'

urlpatterns = [
	path('', views.home, name='home'),
]

blog/urls.py
from django.urls import path, include
from . import views
from django.conf import settings
from django.conf.urls.static import static
from django.contrib.auth.views import LoginView, LogoutView

app_name = 'blog'

urlpatterns = [
	path('', views.blog, name='blog'),
	path('post_detail/<slug:slug>/', views.post_detail, name='post_detail'),
]

parsa/urls.py
from django.contrib import admin
import os
from django.contrib.auth import views as auth_views
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('base.urls')),
    path('shop/', include('shop.urls')),
    path('blog/', include('blog.urls')),
    path('user/', include('user.urls')),
    path('logout/', auth_views.LogoutView.as_view(template_name='user/login.html'), name='logout'),
] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

shop/urls.py
from django.urls import path, include
from . import views
from django.conf import settings
from django.conf.urls.static import static

app_name = 'shop'

urlpatterns = [
	path('instagram/<int:product_id>', views.instagram, name="instagram"),
	path('<int:category_id>', views.shop, name='shop'),
	path('buy/<int:product_id>', views.buy, name='buy'),
	path('product/<int:product_id>', views.product, name='product'),
	path('save_sell/<int:product_id>', views.save_sell, name='save_sell'),
]

user/urls.py
from django.urls import path, include
from . import views
from django.conf import settings
from django.conf.urls.static import static
from django.contrib.auth.views import LoginView, LogoutView

app_name = 'user'

urlpatterns = [
	path('', views.profile, name='profile'),
	path('check/', views.check, name='check'),
	path('login/', views.login_view, name='login_view'),
]

base/models.py
from django.db import models
from django.contrib.auth.models import User

class Group(models.Model):
	name = models.CharField(max_length=200)
	user = models.ManyToManyField(User)

	def __str__(slef):
		return self.name

blog/models.py
from django.db import models
from django.contrib.auth.models import User
from django.utils import timezone

STATUS = (
    (0,"Draft"),
    (1,"Publish")
)

class Post(models.Model):
    title = models.CharField(max_length = 200, unique = True)
    slug = models.SlugField(max_length = 200, unique = True)
    author = models.ForeignKey(User, on_delete = models.CASCADE, related_name = 'blog_posts')
    updated_on = models.DateTimeField(auto_now = True)
    content = models.TextField()
    created_on = models.DateTimeField(auto_now_add = True)
    status = models.IntegerField(choices=STATUS, default=0)
    image = models.ImageField(default=None, upload_to='post_image')

    class Meta:
        ordering = ['-created_on']

    def __str__(self):
        return self.title

shop/models.py
from django.db import models
from django.contrib.auth.models import User

class Seller(models.Model):
	user = models.ForeignKey(User, on_delete=models.CASCADE)
	code = models.IntegerField()

	def __str__(self):
		return self.user

STATUS = (
    (1, "قهوه های گانودرما"),
    (2, "ارایشی"),
    (3, "بهداشتی"),
    (4, "مواد غذایی"),
    (5, "شوینده بهداشتی"),
    (6, "منسوجات"),
    (7, "لوازم خانگی"),
    (8, "محصولات گشاورزی"),
   )

class Product(models.Model):
	name = models.CharField(max_length=500)
	image = models.ImageField()
	price = models.IntegerField()
	point = models.FloatField()
	review = models.TextField()
	usage = models.TextField()
	description = models.TextField()
	video = models.FileField()
	cid = models.IntegerField()
	inventory = models.BooleanField(default=True)

	category = models.IntegerField(choices=STATUS, default=1)

	def __str__(self):
		return self.name



class Bought(models.Model):
	product = models.ForeignKey(Product, on_delete=models.CASCADE, related_name='bought')
	user = models.ForeignKey(User, on_delete=models.CASCADE)
	seller = models.ForeignKey(Seller, on_delete=models.CASCADE)
	date = models.DateTimeField(auto_now=True)

class Buy(models.Model):
	user = models.ForeignKey(User, on_delete=models.CASCADE)
	product = models.ForeignKey(Product, on_delete=models.CASCADE)
	date = models.DateTimeField(auto_now=True)
	done = models.BooleanField(default=False)

	def __str__(self):
		return self.user

class Sell(models.Model):
	product = models.ForeignKey(Product, on_delete=models.CASCADE)
	phone = models.CharField(max_length=20)
	address = models.TextField()
	name = models.CharField(max_length=200)
	done = models.BooleanField(default=False)

	def __str__(self):
		return self.name

user/models.py
from django.db import models
from django.contrib.auth.models import User

class Profile(models.Model):
	user = models.ForeignKey(User, on_delete=models.CASCADE)
	image = models.ImageField(upload_to='profile', default='default_profile.png')

	def __str__(self):
		return self.user.email

base/views.py
from django.shortcuts import render, HttpResponse
from shop.models import Product

def home(request):
	products = Product.objects.all().order_by('point')

	context = {
		'products': products,
	}
	return render(request, 'base/home.html', context)

blog/views.py
from django.shortcuts import render, get_object_or_404, redirect
from .models import Post

def blog(request):
	posts = Post.objects.filter(status=1).order_by('-created_on')

	if not posts:
		posts = False

	return render(request, 'blog/blog.html', context={'posts': posts})

def post_detail(request, slug):
	post = get_object_or_404(Post, slug=slug)
	return render(request, 'blog/post_detail.html', context = {'post': post})




# Create your views here.

shop/views.py
from django.shortcuts import render, HttpResponse, get_object_or_404, redirect
from .models import Product, Sell

def shop(request, category_id):
	products = Product.objects.filter(category=category_id)

	context = {
		'products': products,
	}
	return render(request, 'shop/shop.html', context)

def product(request, product_id):
	product = get_object_or_404(Product, pk=product_id)

	context = {
		'product': product,
	}
	return render(request, 'shop/product.html', context)

def buy(request, product_id):
	product = get_object_or_404(Product, pk=product_id)

	context = {
		'product': product,
	}
	return render(request, 'shop/buy.html', context)

def instagram(request, product_id):
	product = get_object_or_404(Product, pk=product_id)

	context = {
		'product': product,
	}
	return render(request, 'shop/instagram.html', context)

def save_sell(request, product_id):
	if request.method == 'POST':

		name = request.POST['name']
		product = get_object_or_404(Product, pk=product_id)
		phone = request.POST['phone']
		address = request.POST['address']

		sell = Sell(product=product, phone=phone, address=address, name=name)
		sell.save()

		return redirect('base:home')
	else:
		return redirect('base:home')

user/views.py
from django.shortcuts import render, HttpResponse, redirect, get_object_or_404
from django.contrib.auth import authenticate, login
from django.contrib.auth.models import User
from django.contrib import messages
from shop.models import Sell, Buy

def login_view(request):
	return render(request, 'user/login.html')

def register_view(request):
	return render(request, 'user/register.html')

def register(request):
	user = request.POST['username']

	return render(request, 'user/profile.html')

def profile(request):
	if request.user.is_authenticated:
		sells = Sell.objects.all()
		buys = Buy.objects.filter(user=request.user)

		context = {
			'sells': sells,
			'buys': buys,
		}
		return render(request, 'user/profile.html', context)
	else:
		return redirect('user:login_view')

def check(request):
	if request.method == 'POST':
		username = request.POST['username']
		password = request.POST['password']

		user = authenticate(request, username=username, password=password)

		if user is not None:
			login(request, user)
			return redirect('user:profile')
		else:
			messages.add_message(request, messages.INFO, 'Bad Username/Password')
			return redirect('user:login_view')

base/templates/base/home.html
<!DOCTYPE html>
<html>
<head>
	<link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">
	<meta charset="utf-8">
	<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-MrcW6ZMFYlzcLA8Nl+NtUVF0sA7MsXsP1UyJoMp4YLEuNSfAP+JcXn/tWtIaxVXM" crossorigin="anonymous"></script>
	<title>Home</title>
	<meta name="viewport" content="width=device-width, initial-scale=1">
</head>

<style type="text/css">
	@media only screen and (min-width: 500px) {
		.grid {          
			display: grid;
			justify-content: space-between; 
			grid-template-columns: 33% 33% 33%;
		}
	}
	@media only screen and (max-width: 500px) {
		.grid {
			display: grid;
			justify-content: space-between; 
			grid-template-columns: 100%;
		}
	}
</style>

<body class="">
	<div>
		<div class="card-header">
			<ul class="nav nav-tabs card-header-tabs">
			  <li class="nav-item">
			    <a class="nav-link active" aria-current="page" href="{% url 'base:home' %}">خانه</a>
			  </li>

			  <li class="nav-item dropdown">
			    <a class="nav-link dropdown-toggle" data-bs-toggle="dropdown" href="#" role="button" aria-expanded="true">فروشگاه</a>
			    <ul class="dropdown-menu">
			      <li><a class="dropdown-item" href="{% url 'shop:shop' 1 %}">قهوه های گانودرما</a></li>
			      <li><a class="dropdown-item" href="{% url 'shop:shop' 2 %}">ارایشی</a></li>
			      <li><a class="dropdown-item" href="{% url 'shop:shop' 3 %}">بهداشتی</a></li>
			      <li><a class="dropdown-item" href="{% url 'shop:shop' 4 %}">مواد غذایی</a></li>
			      <li><a class="dropdown-item" href="{% url 'shop:shop' 5 %}">شوینده بهداشتی</a></li>
			      <li><a class="dropdown-item" href="{% url 'shop:shop' 6 %}">منسوجات</a></li>
			      <li><a class="dropdown-item" href="{% url 'shop:shop' 7 %}">لوازم خانگی</a></li>
			      <li><a class="dropdown-item" href="{% url 'shop:shop' 8 %}">محصولات کشاورزی</a></li>

			    </ul>
			  </li>

			  <li class="nav-item">
			    <a class="nav-link" href="{% url 'blog:blog' %}">بلاگ</a>
			  </li>
			  <li class="nav-item">
			    <a class="nav-link" href="{% url 'user:profile' %}">
			    	{% if user.is_authenticated %}
			    		پروفایل
			    	{% else %}
			    		ورود
			    	{% endif %}
			    </a>
			  </li>
			</ul>
		</div>

		<div class="m-3 p-3">
			<h3 class="card-text text-success">Welcome {{ user }}</h3><br>
			<h6 class="text-end">محصولات پرطرفدار</h6>

			<div class="grid mt-3">
				{% for product in products %}
					<div class="card mb-2">
					  <a href="{% url 'shop:product' product.id %}"><img src="{{ product.image.url }}" class="card-img-top" alt="...">
					  	
					  </a>
					  <div class="card-body">
					    <p class="card-title">{{ product.name }}</p>
					  </div>
					</div>
				{% endfor %}
			</div>


		</div>

	</div>
</body>
</html>

blog/templates/blog/blog.html
{% load static %}
<!DOCTYPE html>
<html>
<head>
	<link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">
	<meta charset="utf-8">
	<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-MrcW6ZMFYlzcLA8Nl+NtUVF0sA7MsXsP1UyJoMp4YLEuNSfAP+JcXn/tWtIaxVXM" crossorigin="anonymous"></script>
	<title>Blog</title>
	<meta name="viewport" content="width=device-width, initial-scale=1">
</head>
<body>

	<div class="">
		<div class="card-header">
	      <ul class="nav nav-tabs card-header-tabs">
	        <li class="nav-item">
	          <a class="nav-link" aria-current="page" href="{% url 'base:home' %}">خانه</a>
	        </li>

	        <li class="nav-item dropdown">
	          <a class="nav-link dropdown-toggle" data-bs-toggle="dropdown" href="#" role="button" aria-expanded="true">فروشگاه</a>
	          <ul class="dropdown-menu">
	            <li><a class="dropdown-item" href="{% url 'shop:shop' 1 %}">قهوه های گانودرما</a></li>
	            <li><a class="dropdown-item" href="{% url 'shop:shop' 2 %}">ارایشی</a></li>
	            <li><a class="dropdown-item" href="{% url 'shop:shop' 3 %}">بهداشتی</a></li>
	            <li><a class="dropdown-item" href="{% url 'shop:shop' 4 %}">مواد غذایی</a></li>
	            <li><a class="dropdown-item" href="{% url 'shop:shop' 5 %}">شوینده بهداشتی</a></li>
	            <li><a class="dropdown-item" href="{% url 'shop:shop' 6 %}">منسوجات</a></li>
	            <li><a class="dropdown-item" href="{% url 'shop:shop' 7 %}">لوازم خانگی</a></li>
	            <li><a class="dropdown-item" href="{% url 'shop:shop' 8 %}">محصولات کشاورزی</a></li>

	          </ul>
	        </li>

	        <li class="nav-item">
	          <a class="nav-link active" href="{% url 'blog:blog' %}">بلاگ</a>
	        </li>
	        <li class="nav-item">
	          <a class="nav-link" href="{% url 'user:profile' %}">
	            {% if user.is_authenticated %}
	              پروفایل
	            {% else %}
	              ورود
	            {% endif %}
	          </a>
	        </li>
	      </ul>
	    </div>

		<div class="m-3">
			{% if posts == False %}
				<div class="alert alert-danger">there is no post yet</div>
			{% else %}
			<div class="col-10">
				{% for post in posts %}
					<div class="card" style="width: 18rem;">
					  <img src="{{ post.image.url }}" class="card-img-top" alt="...">
					  <div class="card-body">
					    <h5 class="card-title">{{ post.title }}</h5>
					    <p class="card-text">{{post.content|slice:":200" }}</p>
					    <a href="{% url 'blog:post_detail' post.slug  %}" class="btn btn-primary">Read More &rarr;</a>
					  </div>
					</div>
				{% endfor %}
			</div>
			{% endif %}
		</div>
	</div>

</body>
</html>

shop/templates/shop/buy.html
<!DOCTYPE html>
<html>
<head>
	<link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">
	<meta charset="utf-8">
  <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-MrcW6ZMFYlzcLA8Nl+NtUVF0sA7MsXsP1UyJoMp4YLEuNSfAP+JcXn/tWtIaxVXM" crossorigin="anonymous"></script>
	<title>Buy</title>
  <meta name="viewport" content="width=device-width, initial-scale=1">
</head>
<body class="">
	<div>
		<div class="card-header">
      <ul class="nav nav-tabs card-header-tabs">
        <li class="nav-item">
          <a class="nav-link" aria-current="page" href="{% url 'base:home' %}">خانه</a>
        </li>

        <li class="nav-item dropdown">
          <a class="nav-link dropdown-toggle active" data-bs-toggle="dropdown" href="#" role="button" aria-expanded="true">فروشگاه</a>
          <ul class="dropdown-menu">
            <li><a class="dropdown-item" href="{% url 'shop:shop' 1 %}">قهوه های گانودرما</a></li>
            <li><a class="dropdown-item" href="{% url 'shop:shop' 2 %}">ارایشی</a></li>
            <li><a class="dropdown-item" href="{% url 'shop:shop' 3 %}">بهداشتی</a></li>
            <li><a class="dropdown-item" href="{% url 'shop:shop' 4 %}">مواد غذایی</a></li>
            <li><a class="dropdown-item" href="{% url 'shop:shop' 5 %}">شوینده بهداشتی</a></li>
            <li><a class="dropdown-item" href="{% url 'shop:shop' 6 %}">منسوجات</a></li>
            <li><a class="dropdown-item" href="{% url 'shop:shop' 7 %}">لوازم خانگی</a></li>
            <li><a class="dropdown-item" href="{% url 'shop:shop' 8 %}">محصولات کشاورزی</a></li>

          </ul>
        </li>

        <li class="nav-item">
          <a class="nav-link" href="{% url 'blog:blog' %}">بلاگ</a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="{% url 'user:profile' %}">
            {% if user.is_authenticated %}
              پروفایل
            {% else %}
              ورود
            {% endif %}
          </a>
        </li>
      </ul>
    </div>

        <div>
          <div class="card p-3 m-3">
              <form action="{% url 'shop:save_sell' product.id %}" method="POST" class="row g-3">
                {% csrf_token %}
                <div class="col-md-6">
                  <label for="inputName" class="form-label">Name</label>
                  <input type="name" name="name" class="form-control" placeholder="نام" id="inputName">
                </div>
                <div class="col-md-6">
                  <label for="inputPhone" class="form-label">Phone</label>
                  <input type="phone" name="phone" class="form-control" placeholder="شماره تلفن" id="inputPhone">
                </div>
                <div class="col-12">
                  <label for="inputAddress" class="form-label">Address</label>
                  <input type="text" name="address" class="form-control" id="inputAddress" placeholder="ادرس">
                </div>
                <div class="col-12">
                  
                </div>
                <div class="col-12">
                  <button type="submit" class="btn btn-primary">ذخیره</button>
                </div>
              </form>
          </div>
        </div>


	</div>
</body>
</html>

shop/templates/shop/product.html
<!DOCTYPE html>
<html>
<head>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">
    <meta charset="utf-8">
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-MrcW6ZMFYlzcLA8Nl+NtUVF0sA7MsXsP1UyJoMp4YLEuNSfAP+JcXn/tWtIaxVXM" crossorigin="anonymous"></script>
    <title>{{ product.name }}</title>
    <meta name="viewport" content="width=device-width, initial-scale=1">
</head>
<body class="">
    <div>
      <div class="card-header">
      <ul class="nav nav-tabs card-header-tabs">
        <li class="nav-item">
          <a class="nav-link" aria-current="page" href="{% url 'base:home' %}">خانه</a>
        </li>

        <li class="nav-item dropdown">
          <a class="nav-link dropdown-toggle active" data-bs-toggle="dropdown" href="#" role="button" aria-expanded="true">فروشگاه</a>
          <ul class="dropdown-menu">
            <li><a class="dropdown-item" href="{% url 'shop:shop' 1 %}">قهوه های گانودرما</a></li>
            <li><a class="dropdown-item" href="{% url 'shop:shop' 2 %}">ارایشی</a></li>
            <li><a class="dropdown-item" href="{% url 'shop:shop' 3 %}">بهداشتی</a></li>
            <li><a class="dropdown-item" href="{% url 'shop:shop' 4 %}">مواد غذایی</a></li>
            <li><a class="dropdown-item" href="{% url 'shop:shop' 5 %}">شوینده بهداشتی</a></li>
            <li><a class="dropdown-item" href="{% url 'shop:shop' 6 %}">منسوجات</a></li>
            <li><a class="dropdown-item" href="{% url 'shop:shop' 7 %}">لوازم خانگی</a></li>
            <li><a class="dropdown-item" href="{% url 'shop:shop' 8 %}">محصولات کشاورزی</a></li>

          </ul>
        </li>

        <li class="nav-item">
          <a class="nav-link" href="{% url 'blog:blog' %}">بلاگ</a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="{% url 'user:profile' %}">
            {% if user.is_authenticated %}
              پروفایل
            {% else %}
              ورود
            {% endif %}
          </a>
        </li>
      </ul>
    </div>

        <div class="m-3 ">
          <div class="card mb-3 shadow">
            <div class="row g-0">
              <div class="col-md-4">
                <img src="{{ product.image.url }}" class="img-fluid rounded-start" alt="...">
              </div>
              <div class="col-md-8">
                <div class="card-body">
                  <p style="float: left;padding: 5px;" class="shadow-sm card-text border border-2 border-warning d-inline rounded-2 text-warning"><svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-star-fill" viewBox="0 0 16 16">
  <path d="M3.612 15.443c-.386.198-.824-.149-.746-.592l.83-4.73L.173 6.765c-.329-.314-.158-.888.283-.95l4.898-.696L7.538.792c.197-.39.73-.39.927 0l2.184 4.327 4.898.696c.441.062.612.636.282.95l-3.522 3.356.83 4.73c.078.443-.36.79-.746.592L8 13.187l-4.389 2.256z"/>
</svg> {{ product.point }}</p>
                  <h5 class="card-title text-end">{{ product.name }}</h5>
                  <p class="card-text text-end">{{ product.review }}</p><br>
                </div>
                <div class="m-3" style="bottom: 0px;">
                  <h5 style="float: right;" class="shadow-sm border border-2 p-1 text-success border-success rounded-3">{{ product.price }} تومان</h5>
                  <a href="{% url 'shop:buy' product.id %}" class="btn btn-primary shadow-sm">ثبت</a>
                </div>
              </div>
            </div>
          </div>

        <div class="card shadow">
          <div class="card-header text-end">
            استفاده
          </div>
          <div class="card-body text-end">
              <p>{{ product.usage }}</p>
          </div>
        </div>

        <br>

        <div class="card shadow mb-3">
          <div class="card-header text-end">
            توضیحات
          </div>
          <div class="card-body text-end">
              <p>{{ product.description }}</p>
          </div>
        </div>
        
      </div>
    </div>

</body>
</html>

shop/templates/shop/shop.html
<!DOCTYPE html>
<html>
<head>
	<link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">
	<meta charset="utf-8">
	<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-MrcW6ZMFYlzcLA8Nl+NtUVF0sA7MsXsP1UyJoMp4YLEuNSfAP+JcXn/tWtIaxVXM" crossorigin="anonymous"></script>
	<title>Shop</title>
	<meta name="viewport" content="width=device-width, initial-scale=1">
</head>

<style type="text/css">
	@media only screen and (min-width: 500px) {
		.grid {          
			display: grid;
			justify-content: space-between; 
			grid-template-columns: 33% 33% 33%;
		}
	}
	@media only screen and (max-width: 500px) {
		.grid {
			display: grid;
			justify-content: space-between; 
			grid-template-columns: 100%;
		}
	}
</style>

<body class="">
	<div>
		<div class="card-header">
			<ul class="nav nav-tabs card-header-tabs">
			  <li class="nav-item">
			    <a class="nav-link " aria-current="page" href="{% url 'base:home' %}">خانه</a>
			  </li>

			  <li class="nav-item dropdown">
			    <a class="nav-link dropdown-toggle active" data-bs-toggle="dropdown" href="#" role="button" aria-expanded="true">فروشگاه</a>
			    <ul class="dropdown-menu">
			      <li><a class="dropdown-item" href="{% url 'shop:shop' 1 %}">قهوه های گانودرما</a></li>
			      <li><a class="dropdown-item" href="{% url 'shop:shop' 2 %}">ارایشی</a></li>
			      <li><a class="dropdown-item" href="{% url 'shop:shop' 3 %}">بهداشتی</a></li>
			      <li><a class="dropdown-item" href="{% url 'shop:shop' 4 %}">مواد غذایی</a></li>
			      <li><a class="dropdown-item" href="{% url 'shop:shop' 5 %}">شوینده بهداشتی</a></li>
			      <li><a class="dropdown-item" href="{% url 'shop:shop' 6 %}">منسوجات</a></li>
			      <li><a class="dropdown-item" href="{% url 'shop:shop' 7 %}">لوازم خانگی</a></li>
			      <li><a class="dropdown-item" href="{% url 'shop:shop' 8 %}">محصولات کشاورزی</a></li>

			    </ul>
			  </li>

			  <li class="nav-item">
			    <a class="nav-link" href="{% url 'blog:blog' %}">بلاگ</a>
			  </li>
			  <li class="nav-item">
			    <a class="nav-link" href="{% url 'user:profile' %}">
			    	{% if user.is_authenticated %}
			    		پروفایل
			    	{% else %}
			    		ورود
			    	{% endif %}
			    </a>
			  </li>
			</ul>
		</div>

		<div class="m-3 grid">
			{% for product in products %}
				<div class="border rounded p-3 mb-2">
					<h5 class="mt-2 float-end text-success">{{ product.price }} تومان </h5>
				  <a href="{% url 'shop:product' product.id %}"><img src="{{ product.image.url }}" class="img-fluid" alt="...">
				  	
				  </a>
				  <div class="">
				    <h5 class="text-end">{{ product.name }}</h5>
				    <p class="text-end">{{ product.review|slice:":100" }} ...</p>

				  </div>
				  <a href="{% url 'shop:product' product.id %}" class="btn btn-primary">اطلاعات بیشتر</a>
				</div>
			{% endfor %}
		</div>
	</div>
</body>
</html>